version: '3.4'

services:
  nnotif-email:
    image: nnotif-postman
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    environment:
      NODE_ENV: development
    ports:
      - 3003:3003
      - 9229:9229
    command: ["npm", "run", "dev"]
