version: '3.4'

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "nnotif"
    volumes:
      - "dbdata:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  nnotif-dynarest:
    image: nnotif-dynarest
    build:
      context: ./nnotif-dynarest
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DB: postgres://postgres:postgres@host.docker.internal:5432/nnotif
      DEFAULT_LIMIT: 128
    ports:
      - 3000:3000
  nnotif-public:
    image: nnotif-public
    build:
      context: ./nnotif-public
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DYNAREST: http://host.docker.internal:3000
    ports:
      - 3001:3001
  nnotif-email:
    image: nnotif-email
    build:
      context: ./nnotif-email
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
volumes:
  dbdata: {}