GET http://localhost:3000/Resource/resource

###

GET http://localhost:3001/subs

### 

GET http://localhost:3002/email

### 

@base-url=http://localhost:3000

GET {{base-url}}/List?of=Route

###

GET {{base-url}}/Resource/route

###

POST {{base-url}}/Resource
Content-Type: application/json

{
    "type": "Resource",
    "id": "person",
    "of": "Person",
    "desc": "Human being",
    "routes": "/List?_of=Route&res-type=Person",
    "status": "/Coding/resource-statuses?code=pending"
}

###

# @name create
POST {{base-url}}/Person
Content-Type: application/json

{
    "type": "Person",
    "name": [{
        "given": ["John"],
        "family": "Doe"
    }],
    "gender": "male"
}
###

GET {{base-url}}/Person/{{create.response.body.id}}

###

DELETE {{base-url}}/Person/{{create.response.body.id}}

###

PUT {{base-url}}/Person/{{create.response.body.id}}
Content-Type: application/json

{
    "name": [{
        "given": ["John", "Martin"],
        "family": "Doe"
    }],
    "gender": "male"
}