GET http://localhost:3005/subs/resource1

###

GET http://localhost:3001/subs

### 

GET http://localhost:3002/email

### 

@base-url=http://localhost:3000

GET {{base-url}}/List?of=Route

###

GET {{base-url}}/Resource/route

###

POST {{base-url}}/Resource
Content-Type: application/json

{
    "type": "Resource",
    "id": "person",
    "of": "Person",
    "desc": "Human being",
    "routes": "/List?_of=Route&res-type=Person",
    "status": "/Coding/resource-statuses?code=pending"
}

###

# @name create
POST {{base-url}}/Person
Content-Type: application/json

{
    "type": "Person",
    "name": [{
        "given": ["John"],
        "family": "Doe"
    }],
    "gender": "male"
}
###

GET {{base-url}}/Person/{{create.response.body.id}}

###

DELETE {{base-url}}/Person/{{create.response.body.id}}

###

PUT {{base-url}}/Person/{{create.response.body.id}}
Content-Type: application/json

{
    "name": [{
        "given": ["John", "Martin"],
        "family": "Doe"
    }],
    "gender": "male"
}

###

PUT http://localhost:3005/subs/338981fb-c1e6-4647-b8fc-3f1d950ea205
Accept: application/json
Content-Type: application/json

{
    "status": "cancelled",
    "name": {
        "given": [
            "John"
        ],
        "family": ["Doe"]
    },
    "email": "nnotif-no-reply@mailinator.com",
    "gender": "male",
    "dob": "1988-04-18",
    "consent": true,
    "newsLetterId": "f03aad4e"
}

###

GET http://localhost:3001/subs/10c9aeb5-2d11-4038-aebb-79638445b0c1