apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nnotif-dynarest.fullname" . }}
  labels:
    {{- include "nnotif-dynarest.labels" . | nindent 4 }}
type: Opaque
data:
  db: {{ .Values.env.db | b64enc }}
