version: '3.4'

services:
  nnotif-public:
    image: nnotif-public
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DYNAREST: http://localhost:3000
    ports:
      - 3001:3001
