version: '3.4'

services:
  nnotif-public:
    image: nnotif-public
    build:
      context: .
      dockerfile: ./Dockerfile
      target: build
    environment:
      NODE_ENV: development
      DYNAREST: http://localhost:3000
    ports:
      - 3001:3001
      - 9229:9229
    command: ["npm", "run", "dev"]
