version: '3.4'

services:
  nnotif-dynarest:
    image: nnotif-dynarest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DB: postgres://postgres:postgres@localhost:5432/nnotif
      DEFAULT_LIMIT: 128
    ports:
      - 3000:3000
