version: '3.4'

services:
  nnotif-dynarest:
    image: nnotif-dynarest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DB: jdbc:postgresql://host.docker.internal:5432/nnotif?user=postgres&password=postgres
    ports:
      - 3000:3000
