name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build nnotif
      run: |
        docker build ./nnotif-dynarest --file ./nnotif-dynarest/Dockerfile --tag guillerglez88/nnotif-dynarest --tag guillerglez88/nnotif-dynarest:$(date +%s) --target prod
        docker build ./nnotif-public --file ./nnotif-public/Dockerfile --tag guillerglez88/nnotif-public --tag guillerglez88/nnotif-public:$(date +%s) --target prod
        docker build ./nnotif-email --file ./nnotif-email/Dockerfile --tag guillerglez88/nnotif-email --tag guillerglez88/nnotif-email:$(date +%s) --target prod

        ./kube/prod/lint.sh
        ./kube/prod/build.sh
